// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.Api.Modules.Customer;

namespace Microsoft.Extensions.DependencyInjection;

public static class CustomerModuleExtensions
{
    /// <summary>Registers the Customer module's services. Uses the EF Core repository (backed by the application DbContext).</summary>
    public static IServiceCollection AddCustomerModule(this IServiceCollection services)
    {
        services.AddScoped<ICustomerRepository, CustomerEfRepository>();
        return services;
    }
}
