// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ErpBackend.Api.Modules.Customer;

/// <summary>EF Core mapping for Customer. Discovered automatically by ApplyConfigurationsFromAssembly.</summary>
public class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> builder)
    {
        builder.ToTable("Customer");
        builder.Property(e => e.Code).HasMaxLength(20);
        builder.HasIndex(e => e.Code);
        builder.HasIndex(e => e.Name);
        builder.HasIndex(e => e.Email);
        builder.HasIndex(e => e.Segment);
    }
}
