// <auto-generated>Generated from Customer.module.json by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.CrossCutting.Common;

namespace ErpBackend.Api.Modules.Customer;

public class Customer : AuditableEntity
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string? Email { get; set; }
    public string? Segment { get; set; }
}
