// <auto-generated>Generated by erpgen. DO NOT EDIT (custom logic belongs elsewhere).</auto-generated>
#nullable enable
using ErpBackend.CrossCutting.Exceptions;
using ErpBackend.CrossCutting.Extensions;
using ErpBackend.CrossCutting.Pagination;
using ErpBackend.CrossCutting.Responses;
using ErpBackend.CrossCutting.Security;
using ErpBackend.Persistence.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace ErpBackend.Api.Modules.Customer;

[ApiController]
[Route("api/sales/customers")]
[Produces("application/json")]
public class CustomerController(ICustomerRepository repository) : ControllerBase
{
    [HttpGet]
    [HasPermission(CustomerPermissions.View)]
    public async Task<ActionResult<PagedResponse<CustomerDto>>> GetAll([FromQuery] CustomerFilter filter)
    {
        var query = repository.Query();
        if (!string.IsNullOrWhiteSpace(filter.Search))
        {
            var term = filter.Search.Trim().ToLower();
            query = query.Where(e => (e.Code ?? string.Empty).ToLower().Contains(term) || (e.Name ?? string.Empty).ToLower().Contains(term) || (e.Email ?? string.Empty).ToLower().Contains(term) || (e.Segment ?? string.Empty).ToLower().Contains(term));
        }
        if (filter.IsActive.HasValue)
        {
            query = query.Where(e => e.IsActive == filter.IsActive.Value);
        }

        var paged = await query.ToPagedResultAsync(filter);
        var dtos = new PagedResult<CustomerDto>(
            paged.Items.Select(ToDto).ToList(), paged.Meta.Page, paged.Meta.PageSize, paged.Meta.TotalItems);
        return Ok(PagedResponse<CustomerDto>.From(dtos));
    }

    [HttpGet("{id:guid}")]
    [HasPermission(CustomerPermissions.View)]
    public async Task<ActionResult<ApiResponse<CustomerDto>>> GetById(Guid id)
    {
        var entity = await repository.GetAsync(id) ?? throw new NotFoundException("Customer", id);
        return Ok(ApiResponse<CustomerDto>.Ok(ToDto(entity)));
    }

    [HttpPost]
    [HasPermission(CustomerPermissions.Create)]
    public async Task<ActionResult<CreatedResponse<Guid>>> Create([FromBody] CreateCustomerDto dto)
    {
        var entity = new Customer
        {
            Code = dto.Code,
            Name = dto.Name,
            Email = dto.Email,
            Segment = dto.Segment,
            IsActive = true,
        };
        await repository.AddAsync(entity);
        return StatusCode(StatusCodes.Status201Created, new CreatedResponse<Guid>(entity.Id));
    }

    [HttpPut("{id:guid}")]
    [HasPermission(CustomerPermissions.Update)]
    public async Task<ActionResult<NoContentResponse>> Update(Guid id, [FromBody] UpdateCustomerDto dto)
    {
        var entity = await repository.GetAsync(id) ?? throw new NotFoundException("Customer", id);
        entity.Code = dto.Code;
        entity.Name = dto.Name;
        entity.Email = dto.Email;
        entity.Segment = dto.Segment;
        entity.IsActive = dto.IsActive;
        await repository.UpdateAsync(entity);
        return Ok(new NoContentResponse());
    }

    [HttpDelete("{id:guid}")]
    [HasPermission(CustomerPermissions.Delete)]
    public async Task<ActionResult<NoContentResponse>> Delete(Guid id)
    {
        if (!await repository.RemoveAsync(id))
        {
            throw new NotFoundException("Customer", id);
        }
        return Ok(new NoContentResponse());
    }

    private static CustomerDto ToDto(Customer e) => new()
    {
        Id = e.Id,
        CreatedAt = e.CreatedAt,
        UpdatedAt = e.UpdatedAt,
        IsActive = e.IsActive,
        Code = e.Code,
        Name = e.Name,
        Email = e.Email,
        Segment = e.Segment,
    };
}
