// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using ErpBackend.CrossCutting.Common;

namespace ErpBackend.Api.Modules.Customer;

/// <summary>Read DTO.</summary>
public class CustomerDto : BaseDto
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string? Email { get; set; }
    public string? Segment { get; set; }
}

/// <summary>Create payload (DataAnnotations route through ValidationErrorResponse via AddErpApiValidation).</summary>
public class CreateCustomerDto : BaseCreateDto
{
    [Required]
    [StringLength(20)]
    public string Code { get; set; } = string.Empty;

    [Required]
    public string Name { get; set; } = string.Empty;

    [EmailAddress]
    public string? Email { get; set; }

    public string? Segment { get; set; }
}

/// <summary>Update payload.</summary>
public class UpdateCustomerDto : BaseUpdateDto
{
    [Required]
    [StringLength(20)]
    public string Code { get; set; } = string.Empty;

    [Required]
    public string Name { get; set; } = string.Empty;

    [EmailAddress]
    public string? Email { get; set; }

    public string? Segment { get; set; }

    public bool IsActive { get; set; } = true;
}

/// <summary>Filter (search + isActive + created range inherited from FilterParams).</summary>
public class CustomerFilter : ErpBackend.CrossCutting.Pagination.FilterParams;
