// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.Persistence;
using Microsoft.EntityFrameworkCore;

namespace ErpBackend.Api.Modules.Customer;

/// <summary>EF Core repository for Customer, backed by the application's DbContext.</summary>
public class CustomerEfRepository(DbContext context) : EfRepository<Customer>(context), ICustomerRepository;
