// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
namespace ErpBackend.Api.Modules.Customer;

public static class CustomerPermissions
{
    public const string View = "customers.view";
    public const string Create = "customers.create";
    public const string Update = "customers.update";
    public const string Delete = "customers.delete";
}
