// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.Persistence.Abstractions;

namespace ErpBackend.Api.Modules.Customer;

/// <summary>Async persistence contract for Customer (Query/GetAsync/AddAsync/UpdateAsync/RemoveAsync
/// inherited from <see cref="IRepository{T}"/>). Implemented by the EF or in-memory repository.</summary>
public interface ICustomerRepository : IRepository<Customer>;
