import { ChangeDetectionStrategy, Component, OnInit, inject } from '@angular/core';
import { Validators } from '@angular/forms';
import { GenericPageHeaderComponent, GenericCardComponent, GenericTableComponent, GenericFilterComponent, GenericExportButtonComponent, TableColumn, TableAction, TableConfig, ActionConfig, ActionEvent, FilterFieldConfig, FormFieldConfig, BreadcrumbItem, SelectOption, TABLE_DEFAULTS, CustomValidators, ExportService } from '@erp-platform/core';
import { CrudListBase } from '../_shared/crud-list.base';
import { CustomerService } from './customers.service.generated';
import { Customer } from './customers.model.generated';
import { CUSTOMER_PERMISSIONS } from './customers.permissions.generated';

/**
 * Generated list page for Customer. Composed from shared components + CrudListBase.
 * DO NOT EDIT — regenerated by @erp-platform:module. Put custom logic in a separate file.
 */
@Component({
  selector: 'app-customers-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [GenericPageHeaderComponent, GenericCardComponent, GenericTableComponent, GenericFilterComponent, GenericExportButtonComponent],
  templateUrl: './customers-list.component.generated.html',
})
export class CustomerListComponent extends CrudListBase<Customer> implements OnInit {
  private readonly exportService = inject(ExportService);

  protected readonly service = inject(CustomerService);
  protected readonly entityName = 'Customer';

  private readonly segmentOptions: SelectOption[] = [{ value: "enterprise", label: "Enterprise" }, { value: "smb", label: "SMB" }];

  protected readonly formFields: FormFieldConfig<Customer>[] = [
    { key: 'code', label: "Code", type: 'text', validators: [Validators.required, Validators.maxLength(20)], colSpan: 6 },
    { key: 'name', label: "Name", type: 'text', validators: [Validators.required], colSpan: 6 },
    { key: 'email', label: "Email", type: 'email', validators: [CustomValidators.email()], colSpan: 6 },
    { key: 'segment', label: "Segment", type: 'select', options: this.segmentOptions, colSpan: 6 },
    { key: 'isActive', label: "Status", type: 'switch', colSpan: 6 },
  ];

  readonly breadcrumbs: BreadcrumbItem[] = [
    { label: 'Home', route: '/', icon: 'home' }, { label: "Sales" }, { label: "Customers" },
  ];

  readonly newAction: ActionConfig = { key: 'create', label: 'New Customer', icon: 'add', permission: CUSTOMER_PERMISSIONS.create };

  readonly columns: TableColumn<Customer>[] = [
    { key: 'code', label: "Code", sortable: true, sticky: true },
    { key: 'name', label: "Name", sortable: true },
    { key: 'email', label: "Email" },
    { key: 'segment', label: "Segment" },
    { key: 'isActive', label: "Status", type: 'badge', align: 'center', formatter: (v) => (v ? 'Active' : 'Inactive') },
  ];

  readonly rowActions: TableAction<Customer>[] = [
    { key: 'view', label: 'View', icon: 'visibility' },
    { key: 'edit', label: 'Edit', icon: 'edit', color: 'primary', permission: CUSTOMER_PERMISSIONS.update },
    { key: 'delete', label: 'Delete', icon: 'delete', color: 'warn', permission: CUSTOMER_PERMISSIONS.delete },
  ];

  readonly filterFields: FilterFieldConfig[] = [
    { key: 'code', label: "Code", type: 'text', colSpan: 3 },
    { key: 'segment', label: "Segment", type: 'select', colSpan: 3 },
    { key: 'isActive', label: "Status", type: 'boolean', colSpan: 3 },
  ];

  readonly config: TableConfig = { ...TABLE_DEFAULTS, showSelection: true, multiSelect: true };

  ngOnInit(): void {
    this.load();
  }

  onAction(event: ActionEvent<Customer>): void {
    switch (event.action.key) {
      case 'view': this.openView(event.context); break;
      case 'edit': this.openEdit(event.context); break;
      case 'delete': this.confirmDelete(event.context); break;
    }
  }

  exportCsv(): void {
    this.exportService.exportFromApi('sales/customers/export', 'customers').subscribe();
  }
}
