/** Generated from Customer.module.json — DO NOT EDIT (regenerated by @erp-platform:module). */
export interface Customer extends Record<string, unknown> {
  id: string;
  code: string;
  name: string;
  email: string;
  segment: string;
  isActive: boolean;
  createdAt: string;
}
