import { ChangeDetectionStrategy, Component, OnInit, inject } from '@angular/core';
import { Validators } from '@angular/forms';
import { GenericPageHeaderComponent, GenericCardComponent, GenericTableComponent, GenericFilterComponent, GenericExportButtonComponent, TableColumn, TableAction, TableConfig, ActionConfig, ActionEvent, FilterFieldConfig, FormFieldConfig, BreadcrumbItem, TABLE_DEFAULTS, ExportService } from '@erp-platform/core';
import { CrudListBase } from '../_shared/crud-list.base';
import { ProductService } from './products.service.generated';
import { Product } from './products.model.generated';
import { PRODUCT_PERMISSIONS } from './products.permissions.generated';

/**
 * Generated list page for Product. Composed from shared components + CrudListBase.
 * DO NOT EDIT — regenerated by @erp-platform:module. Put custom logic in a separate file.
 */
@Component({
  selector: 'app-products-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [GenericPageHeaderComponent, GenericCardComponent, GenericTableComponent, GenericFilterComponent, GenericExportButtonComponent],
  templateUrl: './products-list.component.generated.html',
})
export class ProductListComponent extends CrudListBase<Product> implements OnInit {
  private readonly exportService = inject(ExportService);

  protected readonly service = inject(ProductService);
  protected readonly entityName = 'Product';

  protected readonly formFields: FormFieldConfig<Product>[] = [
    { key: 'sku', label: "SKU", type: 'text', validators: [Validators.required], colSpan: 6 },
    { key: 'name', label: "Name", type: 'text', validators: [Validators.required], colSpan: 6 },
    { key: 'price', label: "Price", type: 'number', validators: [Validators.required, Validators.min(0)], colSpan: 6 },
    { key: 'stock', label: "Stock", type: 'number', validators: [Validators.min(0)], colSpan: 6 },
    { key: 'isActive', label: "Status", type: 'switch', colSpan: 6 },
  ];

  readonly breadcrumbs: BreadcrumbItem[] = [
    { label: 'Home', route: '/', icon: 'home' }, { label: "Catalog" }, { label: "Products" },
  ];

  readonly newAction: ActionConfig = { key: 'create', label: 'New Product', icon: 'add', permission: PRODUCT_PERMISSIONS.create };

  readonly columns: TableColumn<Product>[] = [
    { key: 'sku', label: "SKU", sortable: true, sticky: true },
    { key: 'name', label: "Name", sortable: true },
    { key: 'price', label: "Price", sortable: true, type: 'currency', align: 'right' },
    { key: 'stock', label: "Stock", type: 'number', align: 'right' },
    { key: 'isActive', label: "Status", type: 'badge', align: 'center', formatter: (v) => (v ? 'Active' : 'Inactive') },
  ];

  readonly rowActions: TableAction<Product>[] = [
    { key: 'view', label: 'View', icon: 'visibility' },
    { key: 'edit', label: 'Edit', icon: 'edit', color: 'primary', permission: PRODUCT_PERMISSIONS.update },
    { key: 'delete', label: 'Delete', icon: 'delete', color: 'warn', permission: PRODUCT_PERMISSIONS.delete },
  ];

  readonly filterFields: FilterFieldConfig[] = [
    { key: 'sku', label: "SKU", type: 'text', colSpan: 3 },
    { key: 'isActive', label: "Status", type: 'boolean', colSpan: 3 },
  ];

  readonly config: TableConfig = { ...TABLE_DEFAULTS, showSelection: true };

  ngOnInit(): void {
    this.load();
  }

  onAction(event: ActionEvent<Product>): void {
    switch (event.action.key) {
      case 'view': this.openView(event.context); break;
      case 'edit': this.openEdit(event.context); break;
      case 'delete': this.confirmDelete(event.context); break;
    }
  }

  exportCsv(): void {
    this.exportService.exportFromApi('catalog/products/export', 'products').subscribe();
  }
}
