/** Generated from Product.module.json — DO NOT EDIT (regenerated by @erp-platform:module). */
export interface Product extends Record<string, unknown> {
  id: string;
  sku: string;
  name: string;
  price: number;
  stock: number;
  isActive: boolean;
  createdAt: string;
}
