// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.Persistence.Abstractions;

namespace ErpBackend.Api.Modules.Product;

/// <summary>Async persistence contract for Product (Query/GetAsync/AddAsync/UpdateAsync/RemoveAsync
/// inherited from <see cref="IRepository{T}"/>). Implemented by the EF or in-memory repository.</summary>
public interface IProductRepository : IRepository<Product>;
