// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
namespace ErpBackend.Api.Modules.Product;

public static class ProductPermissions
{
    public const string View = "products.view";
    public const string Create = "products.create";
    public const string Update = "products.update";
    public const string Delete = "products.delete";
}
