// <auto-generated>Generated from Product.module.json by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.CrossCutting.Common;

namespace ErpBackend.Api.Modules.Product;

public class Product : SoftDeleteEntity
{
    public string Sku { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int? Stock { get; set; }
}
