// <auto-generated>Generated by erpgen. DO NOT EDIT (custom logic belongs elsewhere).</auto-generated>
#nullable enable
using ErpBackend.CrossCutting.Exceptions;
using ErpBackend.CrossCutting.Extensions;
using ErpBackend.CrossCutting.Pagination;
using ErpBackend.CrossCutting.Responses;
using ErpBackend.CrossCutting.Security;
using ErpBackend.Persistence.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace ErpBackend.Api.Modules.Product;

[ApiController]
[Route("api/catalog/products")]
[Produces("application/json")]
public class ProductController(IProductRepository repository) : ControllerBase
{
    [HttpGet]
    [HasPermission(ProductPermissions.View)]
    public async Task<ActionResult<PagedResponse<ProductDto>>> GetAll([FromQuery] ProductFilter filter)
    {
        var query = repository.Query();
        if (!string.IsNullOrWhiteSpace(filter.Search))
        {
            var term = filter.Search.Trim().ToLower();
            query = query.Where(e => (e.Sku ?? string.Empty).ToLower().Contains(term) || (e.Name ?? string.Empty).ToLower().Contains(term));
        }
        if (filter.IsActive.HasValue)
        {
            query = query.Where(e => e.IsActive == filter.IsActive.Value);
        }

        var paged = await query.ToPagedResultAsync(filter);
        var dtos = new PagedResult<ProductDto>(
            paged.Items.Select(ToDto).ToList(), paged.Meta.Page, paged.Meta.PageSize, paged.Meta.TotalItems);
        return Ok(PagedResponse<ProductDto>.From(dtos));
    }

    [HttpGet("{id:guid}")]
    [HasPermission(ProductPermissions.View)]
    public async Task<ActionResult<ApiResponse<ProductDto>>> GetById(Guid id)
    {
        var entity = await repository.GetAsync(id) ?? throw new NotFoundException("Product", id);
        return Ok(ApiResponse<ProductDto>.Ok(ToDto(entity)));
    }

    [HttpPost]
    [HasPermission(ProductPermissions.Create)]
    public async Task<ActionResult<CreatedResponse<Guid>>> Create([FromBody] CreateProductDto dto)
    {
        var entity = new Product
        {
            Sku = dto.Sku,
            Name = dto.Name,
            Price = dto.Price,
            Stock = dto.Stock,
            IsActive = true,
        };
        await repository.AddAsync(entity);
        return StatusCode(StatusCodes.Status201Created, new CreatedResponse<Guid>(entity.Id));
    }

    [HttpPut("{id:guid}")]
    [HasPermission(ProductPermissions.Update)]
    public async Task<ActionResult<NoContentResponse>> Update(Guid id, [FromBody] UpdateProductDto dto)
    {
        var entity = await repository.GetAsync(id) ?? throw new NotFoundException("Product", id);
        entity.Sku = dto.Sku;
        entity.Name = dto.Name;
        entity.Price = dto.Price;
        entity.Stock = dto.Stock;
        entity.IsActive = dto.IsActive;
        await repository.UpdateAsync(entity);
        return Ok(new NoContentResponse());
    }

    [HttpDelete("{id:guid}")]
    [HasPermission(ProductPermissions.Delete)]
    public async Task<ActionResult<NoContentResponse>> Delete(Guid id)
    {
        if (!await repository.RemoveAsync(id))
        {
            throw new NotFoundException("Product", id);
        }
        return Ok(new NoContentResponse());
    }

    private static ProductDto ToDto(Product e) => new()
    {
        Id = e.Id,
        CreatedAt = e.CreatedAt,
        UpdatedAt = e.UpdatedAt,
        IsActive = e.IsActive,
        Sku = e.Sku,
        Name = e.Name,
        Price = e.Price,
        Stock = e.Stock,
    };
}
