// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ErpBackend.Api.Modules.Product;

/// <summary>EF Core mapping for Product. Discovered automatically by ApplyConfigurationsFromAssembly.</summary>
public class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.ToTable("Product");
        builder.HasIndex(e => e.Sku);
        builder.HasIndex(e => e.Name);
    }
}
