// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using ErpBackend.CrossCutting.Common;

namespace ErpBackend.Api.Modules.Product;

/// <summary>Read DTO.</summary>
public class ProductDto : BaseDto
{
    public string Sku { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int? Stock { get; set; }
}

/// <summary>Create payload (DataAnnotations route through ValidationErrorResponse via AddErpApiValidation).</summary>
public class CreateProductDto : BaseCreateDto
{
    [Required]
    public string Sku { get; set; } = string.Empty;

    [Required]
    public string Name { get; set; } = string.Empty;

    [Required]
    [Range(typeof(decimal), "0", "79228162514264337593543950335")]
    public decimal Price { get; set; }

    [Range(0, int.MaxValue)]
    public int? Stock { get; set; }
}

/// <summary>Update payload.</summary>
public class UpdateProductDto : BaseUpdateDto
{
    [Required]
    public string Sku { get; set; } = string.Empty;

    [Required]
    public string Name { get; set; } = string.Empty;

    [Required]
    [Range(typeof(decimal), "0", "79228162514264337593543950335")]
    public decimal Price { get; set; }

    [Range(0, int.MaxValue)]
    public int? Stock { get; set; }

    public bool IsActive { get; set; } = true;
}

/// <summary>Filter (search + isActive + created range inherited from FilterParams).</summary>
public class ProductFilter : ErpBackend.CrossCutting.Pagination.FilterParams;
