// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.Persistence;
using Microsoft.EntityFrameworkCore;

namespace ErpBackend.Api.Modules.Product;

/// <summary>EF Core repository for Product, backed by the application's DbContext.</summary>
public class ProductEfRepository(DbContext context) : EfRepository<Product>(context), IProductRepository;
