// <auto-generated>Generated by erpgen. DO NOT EDIT.</auto-generated>
#nullable enable
using ErpBackend.Api.Modules.Product;

namespace Microsoft.Extensions.DependencyInjection;

public static class ProductModuleExtensions
{
    /// <summary>Registers the Product module's services. Uses the EF Core repository (backed by the application DbContext).</summary>
    public static IServiceCollection AddProductModule(this IServiceCollection services)
    {
        services.AddScoped<IProductRepository, ProductEfRepository>();
        return services;
    }
}
