import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  Rule,
  SchematicContext,
  SchematicsException,
  Tree,
} from '@angular-devkit/schematics';

// ---- Manifest typing (subset used by the frontend generator) ----------------
interface ManifestField {
  name: string;
  type: string;
  label: string;
  required?: boolean;
  validation?: { min?: number; max?: number; minLength?: number; maxLength?: number; pattern?: string; email?: boolean };
  options?: { value: unknown; label: string }[];
  ui?: { list?: boolean; sortable?: boolean; filterable?: boolean; filterType?: string; colSpan?: number; align?: string; badge?: boolean };
}
interface Manifest {
  schemaVersion: string;
  module: { name: string; key: string; pluralName?: string; displayName?: string; icon?: string; navigation?: { menuSection?: string } };
  entity: { idType?: string; base?: string; fields: ManifestField[] };
  permissions?: { prefix?: string };
  list?: { selection?: 'none' | 'single' | 'multiple'; defaultSort?: { field: string; direction?: string } };
  api?: { basePath?: string; resource?: string };
  features?: { exportable?: boolean; filterable?: boolean };
}

interface Options { manifest: string; project?: string }

// ---- Helpers ----------------------------------------------------------------
const upperSnake = (pascal: string) =>
  pascal.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();

function tsType(f: ManifestField): string {
  switch (f.type) {
    case 'number': case 'decimal': case 'currency': return 'number';
    case 'boolean': return 'boolean';
    case 'multiselect': return 'string[]';
    default: return 'string';
  }
}
function columnType(f: ManifestField): string | null {
  if (f.ui?.badge) return 'badge';
  switch (f.type) {
    case 'currency': return 'currency';
    case 'number': case 'decimal': return 'number';
    case 'boolean': return 'boolean';
    case 'date': return 'date';
    case 'datetime': return 'datetime';
    default: return null;
  }
}
function formFieldType(f: ManifestField): string {
  switch (f.type) {
    case 'boolean': return 'switch';
    case 'currency': case 'decimal': case 'number': return 'number';
    case 'email': return 'email';
    case 'password': return 'password';
    case 'textarea': return 'textarea';
    case 'select': case 'multiselect': case 'reference': return 'select';
    case 'date': case 'datetime': return 'date';
    case 'file': return 'file';
    default: return 'text';
  }
}
function filterType(f: ManifestField): string {
  if (f.ui?.filterType) return f.ui.filterType;
  if (f.type === 'boolean') return 'boolean';
  if (f.type === 'select') return 'select';
  return 'text';
}

interface ValidatorBuild { literal: string; usesValidators: boolean; usesCustom: boolean }
function fieldValidators(f: ManifestField): ValidatorBuild {
  const parts: string[] = [];
  let usesValidators = false;
  let usesCustom = false;
  if (f.required) { parts.push('Validators.required'); usesValidators = true; }
  if (f.type === 'email' || f.validation?.email) { parts.push('CustomValidators.email()'); usesCustom = true; }
  if (f.validation?.minLength !== undefined) { parts.push(`Validators.minLength(${f.validation.minLength})`); usesValidators = true; }
  if (f.validation?.maxLength !== undefined) { parts.push(`Validators.maxLength(${f.validation.maxLength})`); usesValidators = true; }
  if (f.validation?.min !== undefined) { parts.push(`Validators.min(${f.validation.min})`); usesValidators = true; }
  if (f.validation?.max !== undefined) { parts.push(`Validators.max(${f.validation.max})`); usesValidators = true; }
  if (f.validation?.pattern) { parts.push(`Validators.pattern(${JSON.stringify(f.validation.pattern)})`); usesValidators = true; }
  return { literal: `[${parts.join(', ')}]`, usesValidators, usesCustom };
}

// ---- Content builders -------------------------------------------------------
function buildModel(m: Manifest): string {
  const idTs = m.entity.idType === 'int' ? 'number' : 'string';
  const lines = m.entity.fields.map((f) => `  ${f.name}: ${tsType(f)};`);
  return `/** Generated from ${m.module.name}.module.json — DO NOT EDIT (regenerated by @erp-platform:module). */
export interface ${m.module.name} extends Record<string, unknown> {
  id: ${idTs};
${lines.join('\n')}
  createdAt: string;
}
`;
}

function buildPermissions(m: Manifest): string {
  const prefix = m.permissions?.prefix ?? m.module.key;
  const constName = `${upperSnake(m.module.name)}_PERMISSIONS`;
  return `/** Generated permission keys for ${m.module.name}. DO NOT EDIT. */
export const ${constName} = {
  view: '${prefix}.view',
  create: '${prefix}.create',
  update: '${prefix}.update',
  delete: '${prefix}.delete',
} as const;
`;
}

function resourcePath(m: Manifest): string {
  const resource = m.api?.resource ?? m.module.key;
  return m.api?.basePath ? `${m.api.basePath}/${resource}` : resource;
}

function buildService(m: Manifest): string {
  const key = m.module.key;
  return `import { Injectable } from '@angular/core';
import { BaseCrudService } from '@erp-platform/core';
import { ${m.module.name} } from './${key}.model.generated';

/** Generated CRUD service for ${m.module.name}. DO NOT EDIT (extend in a separate file if needed). */
@Injectable({ providedIn: 'root' })
export class ${m.module.name}Service extends BaseCrudService<${m.module.name}> {
  protected readonly resource = '${resourcePath(m)}';
}
`;
}

function buildComponent(m: Manifest): { ts: string; html: string } {
  const name = m.module.name;
  const key = m.module.key;
  const plural = m.module.pluralName ?? `${name}s`;
  const permConst = `${upperSnake(name)}_PERMISSIONS`;
  const exportable = m.features?.exportable === true;
  const filterFieldsArr = m.entity.fields.filter((f) => f.ui?.filterable);
  const hasFilters = m.features?.filterable !== false && filterFieldsArr.length > 0;
  const selection = m.list?.selection ?? 'none';

  // Form fields + option consts
  let usesValidators = false;
  let usesCustom = false;
  let usesSelectOption = false;
  const optionConsts: string[] = [];
  const formFieldLines = m.entity.fields.map((f) => {
    const v = fieldValidators(f);
    usesValidators ||= v.usesValidators;
    usesCustom ||= v.usesCustom;
    const colSpan = f.ui?.colSpan ?? 12;
    const parts = [`key: '${f.name}'`, `label: ${JSON.stringify(f.label)}`, `type: '${formFieldType(f)}'`];
    if (v.literal !== '[]') parts.push(`validators: ${v.literal}`);
    if ((f.type === 'select' || f.type === 'multiselect') && f.options?.length) {
      usesSelectOption = true;
      const constName = `${f.name}Options`;
      const opts = f.options.map((o) => `{ value: ${JSON.stringify(o.value)}, label: ${JSON.stringify(o.label)} }`).join(', ');
      optionConsts.push(`  private readonly ${constName}: SelectOption[] = [${opts}];`);
      parts.push(`options: this.${constName}`);
    }
    parts.push(`colSpan: ${colSpan}`);
    return `    { ${parts.join(', ')} },`;
  });

  // Columns (only ui.list fields)
  const listFields = m.entity.fields.filter((f) => f.ui?.list);
  const columnLines = listFields.map((f, i) => {
    const parts = [`key: '${f.name}'`, `label: ${JSON.stringify(f.label)}`];
    if (f.ui?.sortable) parts.push('sortable: true');
    if (i === 0) parts.push('sticky: true');
    const ct = columnType(f);
    if (ct) parts.push(`type: '${ct}'`);
    if (f.ui?.align) parts.push(`align: '${f.ui.align}'`);
    if (f.ui?.badge) parts.push(`formatter: (v) => (v ? 'Active' : 'Inactive')`);
    return `    { ${parts.join(', ')} },`;
  });

  // Filters
  const filterLines = filterFieldsArr.map((f) =>
    `    { key: '${f.name}', label: ${JSON.stringify(f.label)}, type: '${filterType(f)}', colSpan: 3 },`);

  // Imports — all framework symbols come from the package (only what is used).
  const core: string[] = ['GenericPageHeaderComponent', 'GenericCardComponent', 'GenericTableComponent'];
  if (hasFilters) core.push('GenericFilterComponent');
  if (exportable) core.push('GenericExportButtonComponent');
  core.push('TableColumn', 'TableAction', 'TableConfig', 'ActionConfig', 'ActionEvent');
  if (hasFilters) core.push('FilterFieldConfig');
  core.push('FormFieldConfig', 'BreadcrumbItem');
  if (usesSelectOption) core.push('SelectOption');
  core.push('TABLE_DEFAULTS');
  if (usesCustom) core.push('CustomValidators');
  if (exportable) core.push('ExportService');

  const imports: string[] = [
    `import { ChangeDetectionStrategy, Component, OnInit, inject } from '@angular/core';`,
  ];
  if (usesValidators) imports.push(`import { Validators } from '@angular/forms';`);
  imports.push(`import { ${core.join(', ')} } from '@erp-platform/core';`);
  imports.push(`import { CrudListBase } from '../_shared/crud-list.base';`);
  imports.push(`import { ${name}Service } from './${key}.service.generated';`);
  imports.push(`import { ${name} } from './${key}.model.generated';`);
  imports.push(`import { ${permConst} } from './${key}.permissions.generated';`);

  const componentImports = ['GenericPageHeaderComponent', 'GenericCardComponent', 'GenericTableComponent'];
  if (hasFilters) componentImports.push('GenericFilterComponent');
  if (exportable) componentImports.push('GenericExportButtonComponent');

  const configParts = ['...TABLE_DEFAULTS'];
  if (selection !== 'none') configParts.push('showSelection: true');
  if (selection === 'multiple') configParts.push('multiSelect: true');

  const breadcrumbSection = m.module.navigation?.menuSection
    ? `{ label: ${JSON.stringify(m.module.navigation.menuSection)} }, `
    : '';

  const exportMembers = exportable
    ? `\n  private readonly exportService = inject(ExportService);\n`
    : '';
  const exportMethod = exportable
    ? `\n  exportCsv(): void {\n    this.exportService.exportFromApi('${resourcePath(m)}/export', '${key}').subscribe();\n  }\n`
    : '';

  const ts = `${imports.join('\n')}

/**
 * Generated list page for ${name}. Composed from shared components + CrudListBase.
 * DO NOT EDIT — regenerated by @erp-platform:module. Put custom logic in a separate file.
 */
@Component({
  selector: 'app-${key}-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [${componentImports.join(', ')}],
  templateUrl: './${key}-list.component.generated.html',
})
export class ${name}ListComponent extends CrudListBase<${name}> implements OnInit {${exportMembers}
  protected readonly service = inject(${name}Service);
  protected readonly entityName = '${name}';
${optionConsts.length ? '\n' + optionConsts.join('\n') + '\n' : ''}
  protected readonly formFields: FormFieldConfig<${name}>[] = [
${formFieldLines.join('\n')}
  ];

  readonly breadcrumbs: BreadcrumbItem[] = [
    { label: 'Home', route: '/', icon: 'home' }, ${breadcrumbSection}{ label: ${JSON.stringify(plural)} },
  ];

  readonly newAction: ActionConfig = { key: 'create', label: 'New ${name}', icon: 'add', permission: ${permConst}.create };

  readonly columns: TableColumn<${name}>[] = [
${columnLines.join('\n')}
  ];

  readonly rowActions: TableAction<${name}>[] = [
    { key: 'view', label: 'View', icon: 'visibility' },
    { key: 'edit', label: 'Edit', icon: 'edit', color: 'primary', permission: ${permConst}.update },
    { key: 'delete', label: 'Delete', icon: 'delete', color: 'warn', permission: ${permConst}.delete },
  ];
${hasFilters ? `
  readonly filterFields: FilterFieldConfig[] = [
${filterLines.join('\n')}
  ];
` : ''}
  readonly config: TableConfig = { ${configParts.join(', ')} };

  ngOnInit(): void {
    this.load();
  }

  onAction(event: ActionEvent<${name}>): void {
    switch (event.action.key) {
      case 'view': this.openView(event.context); break;
      case 'edit': this.openEdit(event.context); break;
      case 'delete': this.confirmDelete(event.context); break;
    }
  }
${exportMethod}}
`;

  // HTML
  const exportSlot = exportable
    ? `\n    <app-generic-export-button page-header-content [types]="['csv']" (exportClick)="exportCsv()" />`
    : '';
  const filterCard = hasFilters
    ? `\n  <app-generic-card>\n    <app-generic-filter [fields]="filterFields" (filterChange)="onFilter($event)" />\n  </app-generic-card>\n`
    : '';
  const html = `<div class="page">
  <app-generic-page-header
    title="${plural}"
    [breadcrumbs]="breadcrumbs"
    [primaryAction]="newAction"
    (actionClick)="openCreate()">${exportSlot}
  </app-generic-page-header>
${filterCard}
  <app-generic-card>
    <app-generic-table
      [columns]="columns"
      [data]="rows()"
      [config]="config"
      [rowActions]="rowActions"
      [loading]="loading()"
      [page]="page"
      [pageSize]="pageSize"
      [totalItems]="total()"
      (pageChange)="onPage($event)"
      (sortChange)="onSort($event)"
      (actionClick)="onAction($event)">
    </app-generic-table>
  </app-generic-card>
</div>
`;
  return { ts, html };
}

// ---- Tree helpers -----------------------------------------------------------
function write(tree: Tree, path: string, content: string): void {
  if (tree.exists(path)) tree.overwrite(path, content);
  else tree.create(path, content);
}

function insertBeforeMarker(content: string, marker: string, snippet: string): string {
  const idx = content.indexOf(marker);
  if (idx === -1) throw new SchematicsException(`Marker "${marker}" not found; cannot patch idempotently.`);
  const lineStart = content.lastIndexOf('\n', idx) + 1;
  return content.slice(0, lineStart) + snippet + content.slice(lineStart);
}

// ---- Schematic factory ------------------------------------------------------
export function moduleSchematic(options: Options): Rule {
  return (tree: Tree, context: SchematicContext) => {
    if (!options.manifest) throw new SchematicsException('Option "manifest" is required.');

    const manifestPath = resolve(process.cwd(), options.manifest);
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
    if (!manifest.module?.name || !manifest.module?.key || !manifest.entity?.fields?.length) {
      throw new SchematicsException('Invalid manifest: module.name, module.key and entity.fields are required.');
    }

    const { name, key } = manifest.module;
    const appPath = options.project && options.project !== '.' ? `${options.project.replace(/\/+$/, '')}/src/app` : 'src/app';
    const dir = `${appPath}/features/${key}`;

    const component = buildComponent(manifest);
    write(tree, `${dir}/${key}.model.generated.ts`, buildModel(manifest));
    write(tree, `${dir}/${key}.permissions.generated.ts`, buildPermissions(manifest));
    write(tree, `${dir}/${key}.service.generated.ts`, buildService(manifest));
    write(tree, `${dir}/${key}-list.component.generated.ts`, component.ts);
    write(tree, `${dir}/${key}-list.component.generated.html`, component.html);

    // Patch routes (idempotent)
    const routesPath = `${appPath}/app.routes.ts`;
    const prefix = manifest.permissions?.prefix ?? key;
    const plural = manifest.module.pluralName ?? `${name}s`;
    if (tree.exists(routesPath)) {
      let routes = tree.read(routesPath)!.toString('utf8');
      const importToken = `./features/${key}/${key}-list.component.generated`;
      if (!routes.includes(importToken)) {
        const block =
`  {
    path: '${key}',
    canActivate: [permissionGuard],
    data: { permission: '${prefix}.view', breadcrumb: ${JSON.stringify(plural)} },
    loadComponent: () =>
      import('${importToken}').then((m) => m.${name}ListComponent),
  },

`;
        routes = insertBeforeMarker(routes, '// erp-generated:routes', block);
        tree.overwrite(routesPath, routes);
        context.logger.info(`Route added for /${key}`);
      } else {
        context.logger.info(`Route for /${key} already present — skipped.`);
      }
    }

    // Patch menu (idempotent)
    const menuPath = `${appPath}/app.menu.ts`;
    if (tree.exists(menuPath)) {
      let menu = tree.read(menuPath)!.toString('utf8');
      const routeToken = `route: '/${key}'`;
      if (!menu.includes(routeToken)) {
        const icon = manifest.module.icon ?? 'folder';
        const item = `  { label: ${JSON.stringify(plural)}, icon: '${icon}', route: '/${key}' },\n`;
        menu = insertBeforeMarker(menu, '// erp-generated:menu', item);
        tree.overwrite(menuPath, menu);
        context.logger.info(`Menu entry added for ${plural}`);
      } else {
        context.logger.info(`Menu entry for /${key} already present — skipped.`);
      }
    }

    context.logger.info(`✓ Generated module "${name}" in ${dir}`);
    return tree;
  };
}
